trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: prebuild
  displayName: NPM Install
  jobs:
  - job: jobnpminstall
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'Run script npm install'
- stage: build
  displayName: Build SPA
  isSkippable: false
  jobs:
  - job: BuildSPAJob
    steps:
    - script: npm install & npm run build
      displayName: 'Run script npm run build'
- stage: codecoverage
  displayName: Run Sonar Scan
  trigger: manual
  jobs:
  - job: SonarJob
    steps:
    - script: echo 'hello, world'
      displayName: 'Run script SonarScanner'
- stage: artifact_upload
  displayName: Upload zip file
  dependsOn: build
  jobs:
  - job: ArtifactUploadJob
    steps:
    - script: echo 'hello, file upload'
      displayName: 'Run script File Upload curl command'