trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: prebuild
  displayName: NPM Install
  jobs:
  - job: job npm install
    steps:
    - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'Run script npm install'
- stage: build
  displayName: Build SPA
  isSkippable: false
  jobs:
  - job: BuildSPAJob
    steps:
    - script: |
        npm run build
      displayName: 'Run script npm run build'
- stage: codecoverage
  displayName: Run Sonar Scan
  dependsOn: build
  trigger: manual
  jobs:
  - job: SonarJob
    steps:
    - script: echo 'hello, world'
      displayName: 'Run script SonarScanner'
- stage: Upload artifact zip file
  displayName: Upload zip file
  dependsOn: build
  jobs:
  - job: ArtifactUpload Job
    steps:
    - script: echo 'hello, file upload'
      displayName: 'Run script File Upload curl command'